### ISSUE TITLE
New AOP utilities for Metal.js

### ISSUE THREAD

**Issue by robframpton** [Robert-Frampton/metal-aop#1]
@jbalsas, @eduardolundgren

This project is currently a work in progress. Opening this issue to discuss expected behavior, where this code should be housed, etc.

This is more a less a migration from YUI's `Do` class, and contains almost the same set of functionality, though modified to fit Metal's event emitter/handlers. Here is a list of code examples. Take a look at the tests for more examples.

## Basic example

```javascript
import AOP from 'metal-aop';

class MyClass {
	add(n1, n2) {
		console.log('Add method');

		return n1 + n2;
	}
}

const myClass = new MyClass();

AOP.before(function() {
	console.log('Fires before add method');
}, myClass, 'add');

AOP.after(function() {
	console.log('Fires after add method');
}, myClass, 'add');

myClass.add(1, 2); // Returns 3

// Logs:
// 'Fires before add method'
// 'Add method'
// 'Fires after add method'
```

## Removing a listener

```javascript
const handle = AOP.before(function() {
	console.log('Fires before add method');
}, myClass, 'add');

// handle is an instance of EventHandle

handle.removeListener();
```

## Prevent wrapped function

```javascript
const handle = AOP.before(function() {
	return AOP.prevent();
}, myClass, 'add');
```

## Halting all further behavior

```javascript
const handle = AOP.before(function() {
	return AOP.halt('return value');
}, myClass, 'add');

myClass.add(1, 2); // Returns 'return value'
```

## Modifying return value

```javascript
const handle = AOP.after(function() {
	// AOP.currentRetVal === 3
	return AOP.alterReturn(AOP.currentRetVal + 1);
}, myClass, 'add');

myClass.add(1, 2); // Returns 4
```

This will cover most if not all of Portal's use cases of `A.Do.before` and `A.Do.after`.

The only functionality I didn't being over is the ability to modify the arguments that are passed to the wrapped function, mostly because I didn't see any use cases in our own code, and it seems like a pattern we might not want to follow, but we can easily add it if need be.

**Comment by eduardolundgren** [comment]
@Robert-Frampton that's a good utility. Does it needs EventEmitter? If possible, would be good to keep it as simple as possible, few wrapper functions that do the job.

**Comment by robframpton** [comment]
It's definitely the easiest way to keep track of the handlers. If we removed it we would have to duplicate a little bit of logic from metal-events. It's definitely possible, was just hoping to leverage what we have.

**Comment by eduardolundgren** [comment]
A common AOP functionality is responsible for wrapping a fn with a pre or post behavior when we add events to it becomes an AOP-events-library-style.

What if we keep the AOP wrapping ability in separate functions from the events? So they can be imported and use for the simple scenario.

```js
import {before, after} from 'metal-aop';
function foo() {}
before(foo, ...);
after(foo, ...);
```

Alternatively, with events:

```js
import {beforeWithEvents, afterWithEvents} from 'metal-aop';
function foo() {}
beforeWithEvents(foo, ...);
afterWithEvents(foo, ...);
```

With better function names of course :)

**Comment by robframpton** [comment]
The event part of it ins't really exposed, I'm just leveraging it to keep track of the different pre/post handlers, and to provide a way to remove specific pre/post functions since more than one `before` or `after` function can be added to the same method.

```javascript
import {before} from 'metal-aop';

const obj = {
  method: () => {}
};

// Both will be invoked before obj.method
const handle1 = before(fn1, obj, 'method');
const handle2 = before(fn2, obj, 'method');

// The first is removed, leaving only the second
handle1.removeListener();

obj.method();

// Only fn2 from handle2 is fired
```

**Comment by eduardolundgren** [comment]
Right, the event handler pattern is used to turn off the wrapper, correct?

**Comment by robframpton** [comment]
Yep, exactly.

**Comment by eduardolundgren** [comment]
My personal opinion is that it seems a bit too much to use Event Handler pattern to enable or disable AOP bindings, unfortunately, I don't have a better suggestion.

**Comment by robframpton** [comment]
@eduardolundgren, yeah that makes sense. I went ahead and removed the dependency on metal-events, it's now free of any dependencies.
